name = "Cairo"
uuid = "159f3aea-2a34-519c-b102-8c37f9878175"
version = "1.0.5"

[deps]
Cairo_jll = "83423d85-b0ee-5818-9007-b63ccbeb887a"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
Glib_jll = "7746bdde-850d-59dc-9ae8-88ece973131d"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pango_jll = "36c8627f-9965-5494-a995-c6b170f724f3"

[compat]
Cairo_jll = "1.16.0"
Colors = "0.9, 0.10, 0.11, 0.12"
Glib_jll = "2.59.0"
Graphics = "0.4, 1"
FreeTypeAbstraction = "0.10"
Pango_jll = "1.42.4"
julia = "1.3"

[extras]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Base64", "Random", "Printf", "Test"]
